# Generated by Django 3.0.6 on 2020-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TickerSymbol', models.CharField(max_length=6)),
                ('CurrentPrice', models.DecimalField(decimal_places=3, max_digits=10)),
                ('TodayDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
