# Generated by Django 3.0.6 on 2020-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='CurrentPrice',
            new_name='LastPrice',
        ),
        migrations.AddField(
            model_name='stock',
            name='CompanyName',
            field=models.CharField(default='Company Name', max_length=40),
        ),
        migrations.AddField(
            model_name='stock',
            name='EarningsDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='PercentChange',
            field=models.DecimalField(decimal_places=3, default='2', max_digits=6),
        ),
    ]
