# Generated by Django 3.0.6 on 2020-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_auto_20200621_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='PriceChange',
            field=models.DecimalField(decimal_places=3, default='2.50', max_digits=5),
        ),
    ]
