# Generated by Django 3.0.6 on 2020-06-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0004_stock_pricechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='CompanyDesc',
            field=models.TextField(default='Company Description'),
        ),
        migrations.AddField(
            model_name='stock',
            name='StockType',
            field=models.CharField(choices=[('TCH', 'Tech'), ('TO', 'Tourism'), ('O', 'Oil'), ('HTL', 'Health'), ('BNK', 'Banking'), ('RTN', 'Restaurant'), ('RTL', 'Retail')], default='None', max_length=8),
        ),
    ]
